name: PHP CI
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
      - name: Setup project
        run: make setup
      - name: Run linter
        run: make lint
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test